Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/rocky-9"
  config.vm.network "forwarded_port", guest: 8443, host: 8443, host_ip: "127.0.0.1", auto_correct: false, id: "tcp"
  config.vm.network "forwarded_port", guest: 22, host: 2220, host_ip: "127.0.0.1", auto_correct: false, id: "ssh"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "wslrocky9pax"
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = "2"
  end
  #
  # Run Ansible from the Vagrant Host
  #
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.verbose = "v"
    ansible.playbook = "provisioning/setup_machine.yml"
  end
end
